on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
name: Tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Test
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PACKIT_GITHUB_ACCESS_TOKEN }}
        run: hatch test
      - name: Lint
        run: hatch fmt --check